# serverless.yml

service: fractalclock

provider:
  name: aws
  runtime: nodejs14.x

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
